version: '3.8'

services:
  app:
    build: .
    container_name: go-graphql-app
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017
      MONGO_DB: employeeDB
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
