// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Position string `json:"position"`
}

type Mutation struct {
}

type NewEmployee struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Position string `json:"position"`
}

type Query struct {
}
